# To create a user:password pair, the following command can be used:
# htpasswd -nb user password

# http routing section
http:

  routers:
    # Define a connection between requests and services
    isp02:
      rule: "Host(`isp02.domain.tld`)"
       # If the rule matches, applies the middleware
      middlewares:
      - isp02
      # If the rule matches, forward to the service declared below
      service: isp02
      tls:
        certResolver: hetznerdns

  middlewares:
    # Define an authentication mechanism
    isp02:
      basicAuth:
        users:
        # test / test
          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
        removeheader: true

  services:
    
    # Define how to reach an existing service on our infrastructure
    isp02:
      loadBalancer:
        servers:
        - url: http://isp02internal
